<?php   
    define('COMPONENT_PATH','component/') ;
    define('IMG_PATH','images/');
    define('CSS_PATH','css/');
    define('JS_PATH','js/');
    define('AUDIO_PATH','audio/');
    define('PAGES_PATH','pages/');
    define('VENDOR_PATH','vendor/');
    define('VIDEO_PATH','video/');
    define('LIBS_PATH','libs/');
    define('CONTENT_PATH','content/');
    define('HEADER_PATH','header/');
    define('FOOTER_PATH','footer/');
    define('LAYOUT_PATH','layout/');
    define('REUSE_PATH','reuse/');
    define('DIST_PATH','dist/');
    define('ASSETS_PATH','assets/');
    define('DATABASE_PATH','database/')
?>